### ISSUE TITLE
"小数据福音！BERT在极小数据下带来显著提升的开源实现"这篇文章是介绍的文本分类的教程还是介绍的MRPC的任务教程？

### ISSUE THREAD

**Issue by yanqiangmiffy** [Socialbird-AILab/BERT-Classification-Tutorial#1]
"小数据福音！BERT在极小数据下带来显著提升的开源实现"这篇文章是介绍的文本分类的教程还是介绍的MRPC的任务教程？如果是原先的MPRC任务，不需要修改run_classifier.py文件吧

**Comment by yanqiangmiffy** [comment]
文本分类

**Comment by tianke0711** [comment]
@yanqiangmiffy 在吗。我想问一下新的分类文本的num_labels 在哪里修改 为什么我的有error
https://github.com/Socialbird-AILab/BERT-Classification-Tutorial/issues/12
