### ISSUE TITLE
怎么使用GPU模式的

### ISSUE THREAD

**Issue by kedimomo** [Socialbird-AILab/BERT-Classification-Tutorial#13]
我安装了 tensorflow-gpu==1.10.0 版本  但是启动的时候  cpu还是爆满的  gpu没有什么明显变化 ，他也提示
INFO:tensorflow:***** Running training *****
INFO:tensorflow:  Num examples = 567
INFO:tensorflow:  Batch size = 32
INFO:tensorflow:  Num steps = 177
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Running train on CPU

**Comment by ejld** [comment]
> 我安装了 tensorflow-gpu==1.10.0 版本 但是启动的时候 cpu还是爆满的 gpu没有什么明显变化 ，他也提示
> INFO:tensorflow:***** Running training *****
> INFO:tensorflow: Num examples = 567
> INFO:tensorflow: Batch size = 32
> INFO:tensorflow: Num steps = 177
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Running train on CPU

这里的Running on CPU，只是说没有在TPU上跑，GPU也是这么显示，看下代码就能看出来。可以看下gpu显存有没有在用，tensorflow 版本gpu用的比较少，看起来你的情况是正常的

**Comment by kedimomo** [comment]
谢谢 ，最后  输出的test_result.tsv
0.1752398	0.11487983	0.17738575	0.003269045	0.0028900176	0.17111737	0.0030842775	0.17112687	0.17831196	0.0026950506
输出了一串向量    这个怎么用来分类的

**Comment by ejld** [comment]
> 谢谢 ，最后 输出的test_result.tsv
> 0.1752398	0.11487983	0.17738575	0.003269045	0.0028900176	0.17111737	0.0030842775	0.17112687	0.17831196	0.0026950506
> 输出了一串向量 这个怎么用来分类的

argmax 就可以，可以参考tutorial: https://mp.weixin.qq.com/s/XmeDjHSFI0UsQmKeOgwnyA

**Comment by kedimomo** [comment]
恩   一开始是从这篇文章找到 这里的    @ejld  那个 argmax 不是找出最大值的吗      具体怎么判断他是属于哪个类别呢  谢谢
现在输入一行  他也只返回一行结果

**Comment by kedimomo** [comment]
@ejld   我知道了  他返回的是每个类别的可能性   O(∩_∩)O谢谢  所以你叫我用argmax   ，恩  还有最后的问题  那个输出结果的排序 是怎么对应起来的

**Comment by liulj-cloud** [comment]
@ejld 训练的时候gpu显存没有在用，应该是用的cpu训练的，速度特别慢，如果用gpu训练需要在代码里配置吗

**Comment by kedimomo** [comment]
@liulj0507   你如果安装的版本是gpu的  就会使用gpu  如果没有就是tensorflow安装有问题
