### ISSUE TITLE
你好，是直接将data下的train.csb和dev.csv文件复制到MRPC目录下是吧，覆盖掉原先的

### ISSUE THREAD

**Issue by yanqiangmiffy** [Socialbird-AILab/BERT-Classification-Tutorial#2]
你好，是直接将data下的train.csb和dev.csv文件复制到MRPC目录下是吧，覆盖掉原先的，覆盖掉好，然后运行报如下错误：
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [10,768] rhs shape= [3668,768]

**Comment by ejld** [comment]
你好，要把之前的checkpoint 文件夹改个名就可以了，输出文件夹不能有不一样的模型

**Comment by ejld** [comment]
> 你好，是直接将data下的train.csb和dev.csv文件复制到MRPC目录下是吧，覆盖掉原先的，覆盖掉好，然后运行报如下错误：
> InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Assign requires shapes of both tensors to match. lhs shape= [10,768] rhs shape= [3668,768]

你好，要把之前的checkpoint 文件夹改个名就可以了，输出文件夹不能有不一样的模型
