### ISSUE TITLE
eval_drop_remainder = True if FLAGS.use_tpu else Falsed

### ISSUE THREAD

**Issue by LinkToPast1990** [Socialbird-AILab/BERT-Classification-Tutorial#3]
CPU下，若eval样本数不能被batch_size整除，则

INFO:tensorflow:  name = input_ids, shape = (?, 128)
INFO:tensorflow:  name = input_mask, shape = (?, 128)
INFO:tensorflow:  name = label_ids, shape = (?,)
INFO:tensorflow:  name = segment_ids, shape = (?, 128)

修改为：eval_drop_remainder = True

**Comment by ejld** [comment]
你好，可以把错误提示发来看一下吗

**Comment by ejld** [comment]
> CPU下，若eval样本数不能被batch_size整除，则
> 
> INFO:tensorflow: name = input_ids, shape = (?, 128)
> INFO:tensorflow: name = input_mask, shape = (?, 128)
> INFO:tensorflow: name = label_ids, shape = (?,)
> INFO:tensorflow: name = segment_ids, shape = (?, 128)
> 
> 修改为：eval_drop_remainder = True

你好，可以把错误提示发来看一下吗

**Comment by LinkToPast1990** [comment]
你好，程序可以运行，估计只是个显示问题
