### ISSUE TITLE
关于多文本分类任务

### ISSUE THREAD

**Issue by jingubang1219** [Socialbird-AILab/BERT-Classification-Tutorial#4]
最近我也在尝试多分类的fine-tuning ，看了paper和源码，感觉直接用run_classifier.py中的ColaProcessor 进行多分类即可，而且不用调整_create_examples这个函数，只需要调整get_labels这个函数中label list。
而且paper中关于fine-tuning的使用也在figure 3 进行了阐述，博主为啥用MRPC？

**Comment by ejld** [comment]
> 最近我也在尝试多分类的fine-tuning ，看了paper和源码，感觉直接用run_classifier.py中的ColaProcessor 进行多分类即可，而且不用调整_create_examples这个函数，只需要调整get_labels这个函数中label list。
> 而且paper中关于fine-tuning的使用也在figure 3 进行了阐述，博主为啥用MRPC？

可以的，_create_examples也要调，可以少调一个None
