### ISSUE TITLE
Tokens difference between bert project and yours. Is run_classifier.py the only changed file? 

### ISSUE THREAD

**Issue by LinkToPast1990** [Socialbird-AILab/BERT-Classification-Tutorial#5]
For English, the tokens are same.
But for Chinese, the tokens are different when I use the same run_classifier.py

Using https://github.com/google-research/bert
INFO:tensorflow:*** Example ***
INFO:tensorflow:guid: train-5
INFO:tensorflow:tokens: [CLS] 1 。 我 住 的 是 靠 马 路 的 标 准 间 。 房 间 内 设 施 简 陋 ， 并 且 的 房 间 玻 璃 窗 户 外 还 有 一 层 幕 墙 玻 璃 ， 而 且 不 能 打 开 ， 导 致 房 间 不 能 自 然 通 风 ， 采 光 不 好 。 [SEP]

Using your project
INFO:tensorflow:*** Example ***
INFO:tensorflow:guid: train-5
INFO:tensorflow:tokens: [CLS] 1 。 我 ##住 ##的 ##是 ##靠 ##马 ##路 ##的 ##标 ##准 ##间 。 房 ##间 ##内 ##设 ##施 ##简 ##陋 ， 并 ##且 ##的 ##房 ##间 ##玻 ##璃 ##窗 ##户 ##外 ##还 ##有 ##一 ##层 ##幕 ##墙 ##玻 ##璃 ， 而 ##且 ##不 ##能 ##打 ##开 ， 导 ##致 ##房 ##间 ##不 ##能 ##自 ##然 ##通 ##风 ， 采 ##光 ##不 ##好 。 [SEP]

**Comment by ejld** [comment]
Hi, this tutorial was meant for English projects, which has a different model and vocab. If you are running Chinese projects, please see the BERT Chinese and BERT Multilingual, however, BERT Chinese would be the better choice if only Chinese data is considered. The Chinese tokenisation is quite different.

**Comment by ejld** [comment]
> For English, the tokens are same.
> But for Chinese, the tokens are different when I use the same run_classifier.py
> 
> Using https://github.com/google-research/bert
> INFO:tensorflow:*** Example ***
> INFO:tensorflow:guid: train-5
> INFO:tensorflow:tokens: [CLS] 1 。 我 住 的 是 靠 马 路 的 标 准 间 。 房 间 内 设 施 简 陋 ， 并 且 的 房 间 玻 璃 窗 户 外 还 有 一 层 幕 墙 玻 璃 ， 而 且 不 能 打 开 ， 导 致 房 间 不 能 自 然 通 风 ， 采 光 不 好 。 [SEP]
> 
> Using your project
> INFO:tensorflow:*** Example ***
> INFO:tensorflow:guid: train-5
> INFO:tensorflow:tokens: [CLS] 1 。 我 ##住 ##的 ##是 ##靠 ##马 ##路 ##的 ##标 ##准 ##间 。 房 ##间 ##内 ##设 ##施 ##简 ##陋 ， 并 ##且 ##的 ##房 ##间 ##玻 ##璃 ##窗 ##户 ##外 ##还 ##有 ##一 ##层 ##幕 ##墙 ##玻 ##璃 ， 而 ##且 ##不 ##能 ##打 ##开 ， 导 ##致 ##房 ##间 ##不 ##能 ##自 ##然 ##通 ##风 ， 采 ##光 ##不 ##好 。 [SEP]

Hi, this tutorial was meant for English projects, which has a different model and vocab. If you are running Chinese projects, please see the BERT Chinese and BERT Multilingual, however, BERT Chinese would be the better choice if only Chinese data is considered. The Chinese tokenisation is quite different.

**Comment by LinkToPast1990** [comment]
yeah, I use the BERT Chinese. Seems they change the tokenize function on Nov. 1, using ' ' instead of '#'.
