### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by shaoerxixiao** [Socialbird-AILab/BERT-Classification-Tutorial#7]
你好，
请问data数据集里为什么没有test.tsv？
最后的参数设置只需设置
flags.DEFINE_string(
    "data_dir", None,
    "The input data dir. Should contain the .tsv files (or other data files) "
    "for the task.")
就可以了吗？
比如在你的项目下，把None改成'/data'吗？
最后运行run_classifier.py这个文件，是这样吗？
谢谢回复〜

**Comment by shaoerxixiao** [comment]
运行后还有这个问题：
Traceback (most recent call last):
  File "/Volumes/Macintosh HHD/work/Bert_test/BERT-Classification-Tutorial/run_classifier.py", line 50, in <module>
    "bert_config_file", None + "bert_config.json",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by ejld** [comment]
> 你好，
> 请问data数据集里为什么没有test.tsv？
> 最后的参数设置只需设置
> flags.DEFINE_string(
> "data_dir", None,
> "The input data dir. Should contain the .tsv files (or other data files) "
> "for the task.")
> 就可以了吗？
> 比如在你的项目下，把None改成'/data'吗？
> 最后运行run_classifier.py这个文件，是这样吗？
> 谢谢回复〜

你好，data里面是样本数据，dev就可以看出效果，可以在自己的数据集上面按dev 的格式制作test。DATA_DIR 是你的数据路径，具体可以看tutorial，里面每一步都有提到

**Comment by fip-lab** [comment]
我也遇到了这个问题，报TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'的错误

**Comment by mushan09** [comment]
> 我也遇到了这个问题，报TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'的错误

我理解的作者的做法是希望能够不用再命令行里面输入很长的调用指令，但是我不清楚他为什么要None+"string"这种写法，在我的python2.7和python3.6均不支持这种语法。你可以直接用`flags.DEFINE_string(
"data_dir", "你的数据目录",
"The input data dir. Should contain the .tsv files (or other data files) "
"for the task.")`

**Comment by ejld** [comment]
> > 我也遇到了这个问题，报TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'的错误
> 
> 我理解的作者的做法是希望能够不用再命令行里面输入很长的调用指令，但是我不清楚他为什么要None+"string"这种写法，在我的python2.7和python3.6均不支持这种语法。你可以直接用`flags.DEFINE_string( "data_dir", "你的数据目录", "The input data dir. Should contain the .tsv files (or other data files) " "for the task.")`



> 运行后还有这个问题：
> Traceback (most recent call last):
> File "/Volumes/Macintosh HHD/work/Bert_test/BERT-Classification-Tutorial/run_classifier.py", line 50, in 
> "bert_config_file", None + "bert_config.json",
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

typo， 已经修复
