### ISSUE TITLE
关于中文二分类问题

### ISSUE THREAD

**Issue by 34127chi** [Socialbird-AILab/BERT-Classification-Tutorial#8]
修改为中文数据源，标签总共两类，每一个类别的数据样本条数是1000
格式类似 character1空格character2空格character3\tlabel
看最终看eval_result.txt文件准确率一直是0.5
但跟了下代码，输入与预期是相同，不知道为什么一直是0.5，有遇到类似的问题吗

**Comment by ejld** [comment]
> 修改为中文数据源，标签总共两类，每一个类别的数据样本条数是1000
> 格式类似 character1空格character2空格character3\tlabel
> 看最终看eval_result.txt文件准确率一直是0.5
> 但跟了下代码，输入与预期是相同，不知道为什么一直是0.5，有遇到类似的问题吗

中文数据需要用BERT chinese/multilingual

**Comment by LinkToPast1990** [comment]
除了楼上所说，还要修改学习率，如1e－6

**Comment by 34127chi** [comment]
> > 修改为中文数据源，标签总共两类，每一个类别的数据样本条数是1000
> > 格式类似 character1空格character2空格character3\tlabel
> > 看最终看eval_result.txt文件准确率一直是0.5
> > 但跟了下代码，输入与预期是相同，不知道为什么一直是0.5，有遇到类似的问题吗
> 
> 中文数据需要用BERT chinese/multilingual

这个之前就已经改过了 确实是学习率的问题 感谢🙏

**Comment by 34127chi** [comment]
> 除了楼上所说，还要修改学习率，如1e－6

对 确实就是学习率 太大了 感谢感谢🙏

**Comment by kedimomo** [comment]
@34127chi   学习率在哪里调的   依据是什么 ?
