### ISSUE TITLE
关于显卡显存

### ISSUE THREAD

**Issue by c0derm4n** [Socialbird-AILab/BERT-Classification-Tutorial#9]
看到您文章里写的，加载BERT使用显存9.5G，请问您使用的是11G显存的单卡还是多个卡并联的？

**Comment by ejld** [comment]
> 看到您文章里写的，加载BERT使用显存9.5G，请问您使用的是11G显存的单卡还是多个卡并联的？

实验里用的是11G的单卡，NVIDIA GeoForce GTX 1080 Ti
